// lib/views/employee_create.dart
import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../controllers/employee_controller.dart';
import '../models/employee.dart';

class EmployeeCreate extends StatefulWidget {
  const EmployeeCreate({super.key});

  @override
  _EmployeeCreateState createState() => _EmployeeCreateState();
}

class _EmployeeCreateState extends State<EmployeeCreate> {
  final _nameController = TextEditingController();
  final _positionController = TextEditingController();
  final _salaryController = TextEditingController();
  late EmployeeController _employeeController;

  @override
  void initState() {
    super.initState();
    _employeeController = EmployeeController(Supabase.instance.client);
  }

  Future<void> _createEmployee() async {
    final name = _nameController.text;
    final position = _positionController.text;
    final salary = double.tryParse(_salaryController.text) ?? 0.0;

    final newEmployee = Employee(
      id: 0,  // ID will be generated by Supabase
      name: name,
      position: position,
      salary: salary,
      createdAt: DateTime.now(),
    );

    await _employeeController.createEmployee(newEmployee);

    Navigator.pop(context);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Create Employee')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            TextField(controller: _nameController, decoration: const InputDecoration(labelText: 'Name')),
            TextField(controller: _positionController, decoration: const InputDecoration(labelText: 'Position')),
            TextField(
              controller: _salaryController,
              decoration: const InputDecoration(labelText: 'Salary'),
              keyboardType: TextInputType.number,
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: _createEmployee,
              child: const Text('Create Employee'),
            ),
          ],
        ),
      ),
    );
  }
}

